defmodule PubQuizzerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :pub_quizzer

  @impl true
  def init(config) do
    if config[:http] && Keyword.get(config[:http], :ip) == {0, 0, 0, 0} do
      port = Keyword.get(config[:http], :port, 4000)

      local_ips =
        :inet.getif()
        |> elem(1)
        |> Enum.reject(fn
          {{1, 0, 0, 0}, _, _} -> true
          _ -> false
        end)
        |> Enum.map(fn {{a, b, c, d}, _, _} -> "  http://#{a}.#{b}.#{c}.#{d}:#{port}" end)

      IO.puts("")
      IO.puts("🌐 Netzwerk-Zugriff:")
      Enum.each(local_ips, &IO.puts(&1))
      IO.puts("")
    end

    {:ok, config}
  end

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_pub_quizzer_key",
    signing_salt: "PNW2iQHH",
    same_site: "Lax",
    max_age: 30 * 24 * 60 * 60
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options], max_frame_size: 1_000_000],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :pub_quizzer,
    gzip: not code_reloading?,
    only: PubQuizzerWeb.static_paths(),
    cache_control_for_etags:
      Application.compile_env(:pub_quizzer, :cache_control_for_etags, "public"),
    cache_control_for_vsn_requests:
      Application.compile_env(:pub_quizzer, :cache_control_for_vsn_requests, "public"),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :pub_quizzer
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug PubQuizzerWeb.Router
end
