import Config

# Configure your database
# E2E tests run against a separate database so they never touch dev data.
config :pub_quizzer, PubQuizzer.Repo,
  database:
    if(System.get_env("E2E") == "1",
      do: Path.expand("../pub_quizzer_e2e.db", __DIR__),
      else: Path.expand("../pub_quizzer_dev.db", __DIR__)
    ),
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.

# In dev the asset URL is not versioned, so a long-lived immutable cache would
# serve stale CSS/JS forever. Never cache in dev.
config :pub_quizzer,
  cache_control_for_etags: "no-cache",
  cache_control_for_vsn_requests: "no-cache"

config :pub_quizzer, PubQuizzerWeb.Endpoint,
  # Binding to 0.0.0.0 allows access from other devices on the network.
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "ZjaCVUbToHob19L+g7c6y1Xb29G6ZJuLMSZahhB6KI4MrcI4jVv92IkUTHbwoEE+",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:pub_quizzer, ~w(--sourcemap=inline --watch)]},
    tailwindcss: {Tailwind, :install_and_run, [:pub_quizzer, ~w(--watch)]}
  ]

# Live reload can cause full page reloads that race with E2E form submissions,
# so it is disabled when Playwright boots the server (E2E=1).
if System.get_env("E2E") != "1" do
  config :pub_quizzer, PubQuizzerWeb.Endpoint,
    live_reload: [
      patterns: [
        ~r{priv/static/(?!uploads/).+},
        ~r{lib/pub_quizzer_web/(controllers|live|components|admin)/.*.(ex|heex)$}
      ]
    ]
end

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Mailer: use Resend when API key is present, otherwise fall back to Local adapter
# (Local adapter emails are viewable at /dev/mailbox)
if System.get_env("RESEND_API_KEY") do
  config :pub_quizzer, PubQuizzer.Mailer,
    adapter: Swoosh.Adapters.Resend,
    api_key: System.get_env("RESEND_API_KEY")
end

# Enable dev routes for dashboard and mailbox
config :pub_quizzer, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
